name: Test Android
on:
  workflow_dispatch:
  push:
    paths:
      - "bdk-ffi/**"
      - "bdk-android/**"
  pull_request:
    paths:
      - "bdk-ffi/**"
      - "bdk-android/**"

# The default Android NDK on the macos-14-arm image is 26.3.11579264
# https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md

permissions: {}

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: "Show default version of NDK"
        run: echo $ANDROID_NDK_ROOT

      - name: "Check out PR branch"
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: "Cache"
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.toml','**/Cargo.lock') }}

      - name: "Set up JDK"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: "Build Android library"
        run: |
          cd bdk-android
          bash ./scripts/build-linux-x86_64.sh

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: "Run Android connected tests"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          script: ./bdk-android/gradlew connectedAndroidTest --console=plain
